version: 2
jobs:
  build_and_push_tag:
    machine: true
    steps:
      - checkout
      - run:
          shell: /bin/bash
          command: |
            npm i --production
            gitbook build . public/docs/
            mkdir ./target
            docker run --rm -it -v $PWD:/w -w /w --entrypoint meteor -m 3G jeroenpeeters/meteord:1.4.3.1 --allow-superuser build ./target --directory --server-only --architecture os.linux.x86_64
            cp Dockerfile ./target/Dockerfile
            docker build -t ictu/docker-dashboard ./target
            docker tag ictu/docker-dashboard ictu/docker-dashboard:${CIRCLE_TAG}
            MAJOR_VERSION=${CIRCLE_TAG/.*}; docker tag ictu/docker-dashboard:${CIRCLE_TAG} ictu/docker-dashboard:${MAJOR_VERSION}
            MINOR_VERSION=${CIRCLE_TAG%.*}; docker tag ictu/docker-dashboard:${CIRCLE_TAG} ictu/docker-dashboard:${MINOR_VERSION}
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push ictu/docker-dashboard
            docker push ictu/docker-dashboard:${CIRCLE_TAG}
            docker push ictu/docker-dashboard:${MINOR_VERSION}
            docker push ictu/docker-dashboard:${MAJOR_VERSION}
  build_and_push_branch:
    machine:
      node:
        version: 8.10.0
    steps:
      - checkout
      - run:
          shell: /bin/bash
          command: |
            node --version
            npm --version
            npm i --production
            gitbook build . public/docs/
            mkdir ./target
            docker run --rm -it -v $PWD:/w -w /w --entrypoint meteor -m 3G jeroenpeeters/meteord:1.4.3.1 --allow-superuser build ./target --directory --server-only --architecture os.linux.x86_64
            cp Dockerfile ./target/Dockerfile
            docker build -t ictu/docker-dashboard:${CIRCLE_BRANCH} ./target          
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push ictu/docker-dashboard:${CIRCLE_BRANCH}       
workflows:
  version: 2
  build_test_push:
    jobs:
      - build_and_push_branch:
          filters:
            tags:
              ignore: /.*/
            branches:
              only: /^feature.*$/              
      - build_and_push_tag:
          filters:
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
            branches:
              ignore: /.*/