graph TD
    subgraph Server1
        ComposeAgent --- DockerDaemon
        Publisher --- DockerDaemon
        Publisher --- MQTT
        Dashboard --- MongoDB
        Dashboard --- MQTT
    end
    subgraph NFS
        RemoteFS --- MQTT
    end