FORMAT: 1A
HOST: http://localhost:3000/api/v2

# Group Apps

An App is a logical named and versioned entity. It serves as a template for
an **Instance**. This ***API*** offers multiple resources to retrieve and modify
different aspects of an App.

## App [/apps/{name}/{version}]
An application is a logical unit of application configuration data.

+ Parameters
  + name: `nginx` (string) - The name of the application
  + version: `latest` (string) - The version of the application

+ Model (application/json)

  ```js
  {
    "id": "MKMZCnLcEJmkjSenJ",
    "name": "nginx",
    "version": "latest"
  }
  ```

### Retrieve an App [GET]
Returns a specific application.

+ Response 200

    [App][]

+ Response 404

### Create an App [PUT]
Creates a new application with the specified name and version. Returns the
App when succesfully created or updated.

+ Response 201

    [App][]

### Delete an App [DELETE]
Delete an application.

+ Response 204
+ Response 404

## Docker Compose [/apps/{name}/{version}/files/dockerCompose]
A Docker compose file associated with an application.

+ Parameters
  + name: `nginx` (string) - The name of the application
  + version: `latest` (string) - The version of the application

+ Model (text/yaml)

        www:
          image: nginx:latest

### Retrieve the Docker compose file [GET]

+ Response 200
  [Docker Compose][]

### Update the Docker compose file [PUT]

+ Request
  [Docker Compose][]
+ Response 201
+ Response 400 (application/json)

  ```js
  {
    "message": "JS-YAML: end of the stream or a document separator is expected at line 2, column 1:....."
  }
  ```


## BigBoat Compose [/apps/{name}/{version}/files/bigboatCompose]
A BigBoat compose file associated with an application.

+ Parameters
  + name: `nginx` (string) - The name of the application
  + version: `latest` (string) - The version of the application

+ Model (text/yaml)

        name: nginx
        version: latest

        www:
          enable_ssh: true

### Retrieve the BigBoat compose file [GET]

+ Response 200
  [BigBoat Compose][]

### Update the BigBoat compose file [PUT]

The BigBoat compose file should be a valid YAML file.
The `name` and `version` properties of the BigBoat Compose file should equal to
the name and version values of the App entity. The request is denied otherwise.

+ Request
  [BigBoat Compose][]
+ Response 201
+ Response 400 (application/json)

  ```js
  {
    "message": "JS-YAML: end of the stream or a document separator is expected at line 2, column 1:....."
  }
  ```

## Applications [/apps]

+ Model (application/json)

  ```js
  [
    {
      "id": "MKMZCnLcEJmkjSenJ",
      ...
    },
    {
      "id": "LENn6QcjnG8WRvAxf",
      ...
    }
  ]
  ```

### Retrieve all Applications [GET]
Returns all applications.

+ Response 200

  [Applications][]

# Group Instance

An Instance is a parameterized App that is deployed for execution.

## Instances [/instances]

+ Model (application/json)

  ```js
  [
    {
      "id": "...",
      ....
    },
    {
      "id": "..."
    }
  ]
  ```

### Retrieve all Instances [GET]
Returns all instances.

+ Response 200
  [Instances][]
