Template.registerHelper 'settings', -> Settings.all()
Template.registerHelper 'isAdminBoard', -> Settings.get('isAdmin')
Template.registerHelper 'hasLocalAppstore', -> not Settings.get('remoteAppstoreUrl')
Template.registerHelper 'userAccountsEnabled', -> Settings.get('userAccountsEnabled')
Template.registerHelper 'isAuthenticated', -> Meteor.userId() or not Settings.get('userAccountsEnabled')
